export default {
  translation: {
    // login module
    welcome: 'أهلا بك',
    validationPasswordError:
      'يجب أن تحتوي كلمة مرورك على 8 أحرف ، وحرف كبير واحد ، وحرف صغير ، ورقم واحد ، وحرف خاص واحد',
    passwordsMustMatch: 'يجب ان تتطابق كلمات المرور',
    signUp: 'سجل',
    Name: 'اسم',
    email: 'البريد الإلكتروني',
    Password: 'كلمة المرور',
    repeatPassword: 'اعد كلمة السر',
    rememberMe: 'تذكرنى',
    signSocial: 'سجل مع حساب التواصل الاجتماعي',
    loginSocial: 'تسجيل الدخول باستخدام الحساب الاجتماعي',
    byTabbing: 'بالنقر فوق "تسجيل" ، فإنك توافق على',
    termsAndConfitions: 'الشروط والأحكام',
    loginErrorMsg:
      'عنوان البريد الإلكتروني أو كلمة المرور التي أدخلتها غير صحيحة أو الحساب غير موجود',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    forgetYourPass: 'نسيت كلمة المرور؟',
    forgetDes:
      'أدخل عنوان بريدك الإلكتروني وسنرسل لك تعليمات لإعادة تعيين كلمة مرورك.',
    continue: 'استمرار',
    skip: 'تخطي',
    login: 'تسجيل الدخول',
    dontHaveAnAccount: 'ليس لديك حساب؟',
    createNewAccount: 'انشاء حساب جديد',
    pickCountry: 'اختر الدولة',
    // end login module
    theme: 'سمة',
    themes: 'ثيمات',
    defaultTheme: 'السمة الافتراضية',
    darkTheme: 'مظهر داكن',
    lightTheme: 'مظهر خفيف',
    typeSomeThing: 'اكتب شيئا...',
    // more
    menu: 'القائمة',
    contactUs: 'اتصل بنا',
    profile: 'الملف الشخصي',
    languages: 'اللغات',
    favorites: 'المفضلة',
    aboutProject: 'عن المشروع',
    aboutUs: 'من نحن',
    shareApp: 'شارك التطبيق',
    // favorites
    // languages
    arabic: 'عربى',
    english: 'English',
    // letters
    letters: 'حروف',
    // Words
    words: 'كلمات',
    writeWord: 'اكتب كلمة ...',
    // phrases
    phrases: 'عبارات',
    writePhrase: 'كتابة عبارة ...',
    selectWord: 'اختر كلمة',
    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    stop: 'إيقاف',
    cancel: 'إلغاء',
    // Numbers
    numbers: 'أرقام',
    writeNumber: 'اكتب الرقم ...',
    // Profile
    profileName: 'اسم الشخصية',
    phone: 'الهاتف المحمول',
    age: 'العمر',
    job: 'وظيفة',
    enterprise: 'المهنة / المؤسسة',
    country: 'بلد',
    additionalDetails: 'تفاصيل اضافية',
    proposals: 'اقتراحات',
    save: 'حفظ',
    deafNoWork: 'أنا أصم ، لا أعمل',
    deafStudent: 'أنا طالب أصم',
    deafWork: 'أنا أعمل أصم',
    deafParent: 'أنا قريب من الصم',
    deafTranslator: 'أنا أترجم لغة الإشارة',
    deafTeacher: 'أنا مدرس في مدرسة أو جمعية للصم',
    studentWantToLearn: 'أنا طالبة جامعية وأريد أن أتعلم لغة الإشارة',
    reperesentorCharity: 'أنا ممثل',
    reperesentorIT: 'أنا ممثل شركة برمجيات',
    interestedOnly: 'أنا أهتم فقط بالأشخاص ذوي الإعاقة',
    other: 'آخر',
  },
};
